sudo: false

language: c

os:
  - linux
  - osx

osx_image: xcode7.3

compiler:
  - gcc

script: ./configure && make -j4 from-scratch && make check && make clean && ./configure --enable-cplusplus && make -j4 && make check && make clean && ./configure --enable-ansi-c && make -j4 && (cd tests; make test1) && (cd tests; make test2) && (cd tests; make test3) && (cd tests; make test4) && (cd tests; make test5)

notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/ddbe4ac173b7fa2b4bed
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
